import React,{useEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Button}from'../../components/ui/button';
import'./chat-source.css';
declare function acquireVsCodeApi():{postMessage:(data:unknown)=>void};
const api=acquireVsCodeApi();
type Message={id:string;role:string;text:string;label?:string;status?:string;output?:string};
type State={sessions:{id:string;title:string;messages:Message[]}[];current:string;busy:boolean};
function Chat(){const[state,set]=useState<State>({sessions:[],current:'',busy:false});const[text,write]=useState('');const end=useRef<HTMLDivElement>(null);
useEffect(()=>{const receive=(e:MessageEvent)=>{if(e.data.type==='state')set(e.data)};window.addEventListener('message',receive);api.postMessage({type:'ready'});return()=>window.removeEventListener('message',receive)},[]);
const messages=state.sessions.find(s=>s.id===state.current)?.messages||[];
useEffect(()=>{end.current?.scrollIntoView({block:'end'})},[state]);
const send=()=>{if(text.trim()&&!state.busy){api.postMessage({type:'send',text});write('')}};
return <main><header><div><strong>Pi / Ori</strong><span>Workspace coding assistant</span></div><Button className="small" disabled={state.busy} onClick={()=>api.postMessage({type:'new'})}>New chat</Button></header><label className="history">Conversation<select aria-label="Coding conversation" disabled={state.busy} value={state.current} onChange={e=>api.postMessage({type:'select',id:e.target.value})}>{state.sessions.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select></label><section className="messages" aria-label="Coding conversation messages">{!messages.length&&<div className="empty"><h2>What shall we build?</h2><p>I can edit files, run commands, install project packages, and build an app in this workspace.</p><p>Model access is preloaded. Your provider key stays in the gateway.</p></div>}{messages.map(m=>m.role==='tool'?<details key={m.id} className="tool"><summary>{m.label}<span>{m.status}</span></summary><pre>{m.text}</pre>{m.output&&<pre className="output">{m.output}</pre>}</details>:<article key={m.id} className={m.role}><span className="speaker">{m.role==='user'?'You':m.role==='error'?'Notice':'Pi'}</span><div className="message-text">{m.text}</div></article>)}<div ref={end}/></section><form onSubmit={e=>{e.preventDefault();send()}}><label htmlFor="prompt">Message Pi</label><textarea id="prompt" aria-label="Message Pi" placeholder="Build a landing page, inspect a file…" value={text} onChange={e=>write(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><div className="actions"><span role="status">{state.busy?'Working in your workspace…':'Luna · xhigh'}</span>{state.busy?<Button type="button" className="small" onClick={()=>api.postMessage({type:'stop'})}>Stop</Button>:<Button className="send" type="submit" disabled={!text.trim()}>Send</Button>}</div></form><footer><button onClick={()=>api.postMessage({type:'terminal'})}>Open agent terminal</button><span>Open App preview in Sandbox Lab to view port 3000.</span></footer></main>}
createRoot(document.getElementById('root')!).render(<Chat/>);
