'use client';
import {ModelCosts} from '@/components/model-costs';
import {useEffect,useState} from 'react';
import {Area,AreaChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {RefreshCw,Activity,Clock,AlertTriangle,Wallet} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {startPolling} from '@/lib/polling';
import {ServiceObservations,type ServiceData,type SupportingData} from '@/components/service-observations';
type Role={running:number;warm:number;busy:number;queued:number;cpu:number;memory_gib:number;retained:number};
type Event={at:number;kind:string;resource:string;event:string;seconds:number|null;exit_code:number|null;error:string|null};
type Data={services?:ServiceData;supporting?:SupportingData;observed_at:number;samples:{at:number;roles:Record<string,Role>;estimated_and_reserved_usd:number}[];events:Event[];totals:{kind:string;event:string;count:number;total_seconds:number;average_seconds:number;failures:number}[];charges:{kind:string;estimated_spent:number;reserved:number;operations:number}[];budget:{estimated_and_reserved_usd:number;billed_usd:number;billing_available?:boolean;operator_reported_spend_usd?:number|null;model_estimated_and_reserved_usd?:number;available_usd:number};max_hourly_compute_usd:number;errors:string[]};
const colors:Record<string,string>={python:'#f0bd79',quick:'#79c7f0',headless:'#bca5ef',developer:'#91d4ac'};
export function OperationsPanel({sessionFetch}:{sessionFetch:(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;provider?:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[metric,setMetric]=useState<'running'|'busy'|'queued'|'cpu'|'memory_gib'>('running'),[onlyFailures,setOnlyFailures]=useState(true);
 useEffect(()=>startPolling({run:async()=>{const r=await sessionFetch('/api/operations');if(!r.ok)throw Error();setData(await r.json());setError('')},interval:()=>15000,onError:()=>setError('Refresh unavailable; the last observation remains visible.')}),[sessionFetch,refresh]);
 const last=data?.samples.at(-1),roles=last?.roles||{},history=data?.samples.map(s=>({at:s.at,...Object.fromEntries(Object.keys(colors).map(k=>[k,s.roles[k]?.[metric]??0]))}))||[];
 const sum=(key:keyof Role)=>Object.values(roles).reduce((n,r)=>n+r[key],0),events=data?.events.filter(e=>!onlyFailures||e.error||e.exit_code||e.event.includes('failed'))||[];
 return <section className="workspace-page collection-page ops-page"><header className="ops-header"><div><p className="eyebrow">AZURE OPERATIONS</p><h1>Usage and reliability</h1><p>Observed allocations, queueing, execution outcomes and testing costs.</p></div><Button variant="outline" onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={16}/>Refresh</Button></header>{error&&<p role="alert">{error}</p>}{!data?<p>Loading measured history…</p>:<>
 <ModelCosts sessionFetch={sessionFetch}/><p className="ops-note">Observed {new Date(data.observed_at*1000).toLocaleTimeString()} · refreshes every 15 seconds · seven-day local history</p>
 <div className="ops-metrics">{[[Activity,'Running / warm',`${sum('running')} / ${sum('warm')}`,'Tracked compute allocations'],[Clock,'Queued',sum('queued'),'Waiting work allocates no compute'],[Wallet,'Azure estimate + reservations',`$${data.budget.estimated_and_reserved_usd.toFixed(2)}`,data.budget.operator_reported_spend_usd!=null?`Operator-reported spend: ~$${data.budget.operator_reported_spend_usd.toFixed(2)}; estimate is not the bill`:data.budget.billing_available?`Azure reported: $${data.budget.billed_usd.toFixed(2)} (delayed)`:'Azure bill not yet available; this is not actual spend'],[AlertTriangle,'Recent failures',data.events.filter(e=>e.error||e.exit_code).length,'Latest 200 lifecycle / command events']].map(([Icon,label,value,detail])=>{const I=Icon as typeof Activity;return <article className="ops-metric" key={String(label)}><div><I size={17}/><span>{String(label)}</span></div><strong>{String(value)}</strong><small>{String(detail)}</small></article>})}</div>
 <article className="ops-card"><div className="ops-card-heading"><h2>Resource history</h2><select aria-label="Resource history metric" value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}><option value="running">Tracked allocations</option><option value="busy">Executing commands</option><option value="queued">Queued starts</option><option value="cpu">Allocated vCPU</option><option value="memory_gib">Allocated memory · GiB</option></select></div><p className="ops-note">CPU and memory show allocated capacity, not measured processor utilization. Empty history means no observation, not zero usage.</p>{history.length?<ResponsiveContainer width="100%" height={280}><AreaChart data={history}><CartesianGrid strokeDasharray="3 3" stroke="#ffffff18"/><XAxis dataKey="at" tickFormatter={t=>new Date(Number(t)*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}/><YAxis allowDecimals={metric==='cpu'||metric==='memory_gib'}/><Tooltip labelFormatter={t=>new Date(Number(t)*1000).toLocaleString()}/><Legend/>{Object.entries(colors).map(([k,c])=><Area key={k} type="stepAfter" dataKey={k} stroke={c} fill={c} fillOpacity={.16} isAnimationActive={false}/>)}</AreaChart></ResponsiveContainer>:<p>History begins with this deployment.</p>}</article>
 <div className="ops-columns"><article className="ops-card"><h2>Current allocation</h2><div className="ops-table-wrap"><table><thead><tr><th>Resource</th><th>Running</th><th>Warm</th><th>Busy</th><th>Queued</th><th>vCPU / GiB</th></tr></thead><tbody>{Object.entries(roles).map(([k,r])=><tr key={k}><td>{k}</td><td>{r.running}</td><td>{r.warm}</td><td>{r.busy}</td><td>{r.queued}</td><td>{r.cpu} / {r.memory_gib}</td></tr>)}</tbody></table></div><p className="ops-note">Aggregate compute guard: ${data.max_hourly_compute_usd}/hour. Headless/developer spares follow the ten-minute demand window. Python pool sessions expire after 55 idle minutes; their allocation count is broker-estimated. Busy project files are never shared with unrelated sessions.</p></article>
 <article className="ops-card"><h2>Cost by resource</h2><div className="ops-table-wrap"><table><thead><tr><th>Resource</th><th>Completed estimate</th><th>Reserved</th></tr></thead><tbody>{data.charges.map(c=><tr key={c.kind}><td>{c.kind}</td><td>${c.estimated_spent.toFixed(4)}</td><td>${c.reserved.toFixed(4)}</td></tr>)}</tbody></table></div><p className="ops-note">Estimates and reservations are not invoices. Azure billing is delayed; the Azure budget includes its initial test estimate and other-cost allowance. Model rows are tracked separately and do not consume the Azure ceiling; OpenRouter uses its separately configured budget.</p></article></div>
 {data.services&&data.supporting&&<ServiceObservations services={data.services} supporting={data.supporting}/>}
 <article className="ops-card"><div className="ops-card-heading"><h2>Lifecycle and failure log</h2><label><input type="checkbox" checked={onlyFailures} onChange={e=>setOnlyFailures(e.target.checked)}/> Failures only</label></div><div className="ops-table-wrap"><table><thead><tr><th>Time</th><th>Resource</th><th>Event</th><th>Duration</th><th>Outcome</th></tr></thead><tbody>{events.map((e,i)=><tr key={i}><td>{new Date(e.at*1000).toLocaleTimeString()}</td><td title={e.resource}>{e.kind} {e.resource.slice(0,8)}</td><td>{e.event}</td><td>{e.seconds==null?'—':`${e.seconds.toFixed(2)}s`}</td><td>{e.error||(e.exit_code==null?'—':`Exit ${e.exit_code}`)}</td></tr>)}</tbody></table></div>{!events.length&&<p>No matching events in the observed history.</p>}<p className="ops-note">Logs exclude prompts, command bodies, files and credentials.</p></article>{data.errors.map(e=><p role="alert" key={e}>{e}</p>)}
 </>}</section>
}
