'use client';
import {AppWindow,ArrowUpRight,ArrowRight,BookOpen,Check,Download,File,FileCode2,FileImage,FileSpreadsheet,FolderOpen,HardDrive,LoaderCircle,MessageSquare,Monitor,Plus,RefreshCw,Trash2,Terminal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Run,Workspace,SavedFile,Project} from '@/lib/lab-types';
import {useState, type ReactNode} from 'react';
import {LinkWorkspace} from '@/components/workspace-sync';
import {StatePill} from '@/components/state-pill';
export {StatePill} from '@/components/state-pill';

import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter} from '@/components/ui/alert-dialog';

function PageHeading({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:ReactNode}) {
 return <header className="collection-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="collection-description">{description}</p></div>{children}</header>;
}
export function AppsView({runs,stale,onOpen,onConversation}:{runs:Run[];stale:boolean;onOpen:(run:Run)=>void;onConversation:(id:string)=>void}) {
 return <section className="workspace-page collection-page"><PageHeading eyebrow="YOUR COLLECTION" title="Apps" description="Pick up where you left off. Sleeping apps wake when you open them."><span className="collection-count">{runs.length} apps</span></PageHeading>
 <div className="apps-grid">{runs.map(run=><article className="app-card" key={run.id}>
   <div className={`app-card-cover ${run.preview_artifact?'reference':''}`}><div className="app-glyph">{run.preview_artifact?<BookOpen size={30} strokeWidth={1.5}/>:<AppWindow size={30} strokeWidth={1.5}/>}</div><StatePill state={stale?'unknown':run.runtime_status||'checking'}/><span className="app-kind">{run.preview_artifact?'FIELD GUIDE':'WORKSPACE APP'}</span></div>
   <div className="app-card-body"><h2>{run.title||'Untitled app'}</h2><p>{run.preview_artifact?'Your guide to execution, storage, security and scale.':'An interactive app with its own saved project.'}</p><div className="app-card-meta"><HardDrive size={13}/>{run.preview_artifact?'Saved reference · no compute needed':'Files retained while sleeping'}</div><div className="card-actions"><Button onClick={()=>onOpen(run)}>Open app <ArrowUpRight size={16}/></Button><Button variant="ghost" onClick={()=>onConversation(run.thread_id)}><MessageSquare size={15}/> Conversation</Button></div></div>
 </article>)}</div>{!runs.length&&<div className="collection-empty"><AppWindow/><h2>Your next idea starts in chat</h2><p>Apps you build will be saved here.</p></div>}</section>;
}
export function WorkspacesView({workspaces,stale,name,setName,starting,onStart,onOpen,onRefresh,onDelete,projects,sessionFetch,onProject,onLinked}:{projects:Project[];sessionFetch:(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;onProject:(id:string)=>void;onLinked:()=>unknown;workspaces:Workspace[];stale:boolean;name:string;setName:(name:string)=>void;starting:boolean;onStart:()=>void;onOpen:(ws:Workspace)=>void;onRefresh:(ws:Workspace)=>void;onDelete:(ws:Workspace)=>Promise<void>}) {
 const [deleting,setDeleting]=useState<Workspace|null>(null);
 const [busy,setBusy]=useState(false);
 const [deleteError,setDeleteError]=useState('');
 return <section className="workspace-page collection-page"><AlertDialog open={!!deleting} onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><AlertDialogContent><AlertDialogTitle>Delete {deleting?.name}?</AlertDialogTitle><AlertDialogDescription>This permanently removes the workspace and its stored files, installed packages and workspace apps. Download anything you want to keep first. The linked project, its chats and its separate chat sandbox are retained.</AlertDialogDescription>{deleteError&&<p role="alert">{deleteError}</p>}<AlertDialogFooter><Button variant="ghost" disabled={busy} onClick={()=>setDeleting(null)}>Cancel</Button><Button variant="destructive" disabled={busy} onClick={async()=>{if(!deleting)return;setBusy(true);setDeleteError('');try{await onDelete(deleting);setDeleting(null);}catch(e){setDeleteError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Deleting…':'Delete workspace'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog><PageHeading eyebrow="YOUR DEVELOPMENT SPACE" title="Workspaces" description="VS Code, a terminal and Pi. A persistent home for your own work."><span className="collection-count">{workspaces.length} workspaces</span></PageHeading>
 <form className="workspace-create-bar" onSubmit={e=>{e.preventDefault();onStart();}}><div className="create-icon"><Plus size={21}/></div><div className="create-copy"><strong>Start a workspace</strong><span>New workstations get a project automatically.</span></div><label className="sr-only" htmlFor="workspace-name">Workspace name</label><input id="workspace-name" value={name} onChange={e=>setName(e.target.value)} pattern="[a-z][a-z0-9-]{0,27}" required placeholder="my-workspace"/><Button disabled={starting} type="submit">{starting?<LoaderCircle className="spin" size={16}/>:<ArrowRight size={16}/>} Start</Button></form>
 <div className="collection-subhead"><span>Personal environments</span><span className="live-note"><i/> Live · refreshes every 5s</span></div>
 <div className="workspace-list">{workspaces.map(ws=><article className="workstation-row" key={ws.id}><div className="workstation-icon"><Monitor size={25}/></div><div className="workstation-info"><div className="workstation-name"><h2>{ws.name}</h2><StatePill state={stale?'unknown':ws.status}/></div><p>VS Code <span>·</span> Pi / Ori <span>·</span> Persistent files</p><div className="workstation-project">{ws.project_id&&<button onClick={()=>onProject(ws.project_id!)}><FolderOpen size={13}/>{ws.project_name||'Project'}</button>}<LinkWorkspace workspace={ws} projects={projects} sessionFetch={sessionFetch} onRefresh={onLinked}/></div>{ws.harness_status&&!ws.harness_status.startsWith('Available')&&!['ready','configured'].includes(ws.harness_status)&&<span className="setup-note">{ws.harness_status}</span>}</div><div className="workstation-actions"><Button disabled={ws.status==='deleting'} onClick={()=>onOpen(ws)}>Open workspace <ArrowUpRight size={16}/></Button><a className="icon-action" href={ws.url} target="_blank" rel="noreferrer" aria-label={`Manage ${ws.name}`} title="Manage workspace"><Monitor size={16}/></a>{ws.status==='running'&&<Button variant="ghost" size="icon" aria-label={`Refresh Pi in ${ws.name}`} onClick={()=>onRefresh(ws)}><RefreshCw size={16}/></Button>}<Button variant="ghost" size="icon" disabled={ws.status==='deleting'} aria-label={`Delete ${ws.name}`} title="Delete workspace" onClick={()=>{setDeleteError('');setDeleting(ws);}}><Trash2 size={16}/></Button></div></article>)}</div>
 {!workspaces.length&&<div className="collection-empty"><Monitor/><h2>A place to build</h2><p>Create a workspace above to open VS Code and Pi.</p></div>}
 <footer className="workspace-details"><div><HardDrive size={18}/><p><strong>Your files stay here</strong><span>Compute sleeps after 10 idle minutes. Opening a workspace wakes it.</span></p></div><div><Terminal size={18}/><p><strong>All your toolchains</strong><span>Python · JavaScript · C#/.NET · Julia · Go · Rust · C/C++ · Shell</span></p></div></footer></section>;
}
const fileInfo=(name:string)=>{
 const ext=name.split('.').pop()?.toLowerCase()||'';
 if(['png','jpg','jpeg','svg','webp'].includes(ext))return {Icon:FileImage,label:'Image',tone:'violet'};
 if(['csv','parquet','json','xlsx'].includes(ext))return {Icon:FileSpreadsheet,label:ext.toUpperCase(),tone:'green'};
 if(['html','htm'].includes(ext))return {Icon:AppWindow,label:'Interactive HTML',tone:'blue'};
 if(['py','js','ts','go','rs','c','cpp','cs','sh','jl'].includes(ext))return {Icon:FileCode2,label:ext.toUpperCase()+' source',tone:'amber'};
 return {Icon:File,label:ext.toUpperCase()||'File',tone:'muted'};
};
const fileSize=(n:number)=>n>=1e6?(n/1e6).toFixed(1)+' MB':n>=1000?(n/1000).toFixed(1)+' KB':n+' B';
export function FilesView({title,files,projectId,loading,onOpen}:{title?:string;files:SavedFile[];projectId:string|null;loading:boolean;onOpen:(f:SavedFile)=>void}) {
 return <section className="workspace-page collection-page"><PageHeading eyebrow="CONVERSATION FILES" title={title||'Choose a conversation'} description={title?'Saved outputs and source from this conversation.':'Open a chat from history to see its saved files.'}><span className="collection-count">{files.length} files</span></PageHeading>
 {title&&<><div className="file-context"><span className="file-context-icon"><FolderOpen size={22}/></span><div><strong>{projectId?'Project connected':'Saved locally'}</strong><p>{projectId?'This conversation also has a persistent project and packages.':'Working files restore into fresh Python compute when needed.'}</p></div><span className="storage-label"><Check size={14}/> Local storage</span></div>
 <div className="files-table"><div className="files-table-header"><span>Name</span><span>Size</span><span>Actions</span></div>{files.map(file=>{const {Icon,label,tone}=fileInfo(file.name);return <article className="file-row" key={file.name}><div className="file-identity"><span className={`file-icon ${tone}`}><Icon size={21}/></span><div><button onClick={()=>onOpen(file)} title={file.name}>{file.name}</button><small>{label}</small></div></div><span className="file-size">{fileSize(file.size)}</span><div className="file-actions"><Button variant="ghost" size="sm" onClick={()=>onOpen(file)}>View <ArrowUpRight size={14}/></Button><a className="icon-action" href={file.download_url} download aria-label={`Download ${file.name}`} title="Download"><Download size={17}/></a></div></article>})}</div>
 {loading&&!files.length?<div className="collection-empty"><LoaderCircle className="spin"/><p>Loading files…</p></div>:!files.length&&<div className="collection-empty"><FolderOpen/><h2>No saved files yet</h2><p>Charts, datasets and source files will appear here as you work.</p></div>}
 <p className="collection-footnote">Each conversation keeps its own files. Stopping compute does not remove saved outputs.</p></>}
 </section>;
}
