'use client';
type CloudService={name:string;type:string;region:string;sku:string|null;status?:string;metrics:Record<string,unknown>;errors:string[]};
export type ServiceData={observed_at:number|null;refreshing:boolean;error:string|null;services:CloudService[]};
export type SupportingData={storage:{current_bytes:number;max_current_bytes:number;checkpoints:number;max_objects:number;weekly_uploaded_bytes:number;weekly_upload_limit_bytes:number;archive_after_days:number;archived_workspaces:number};package_gateway:{loaded:boolean;cached_bytes?:number;capacity_bytes?:number;artifacts?:number;catalog_entries?:number;active_downloads?:number;minimum_age_days?:number};broker:{sdk_workers:number;active_commands:number;pending_cleanup:number};model:{recent_calls:number};identity:{authentication:string;ownership:string};retained:Record<string,number>};
const bytes=(n:number)=>`${(n/1e6).toFixed(1)} MB`;
function policy(type:string){const t=type.toLowerCase();if(t.endsWith('sandboxgroups'))return 'Active CPU/RAM; retained-state storage rate unverified. Stops release compute.';if(t.endsWith('storageaccounts'))return 'Stored bytes, operations and transfer; storage continues when compute stops.';if(t.endsWith('registries'))return 'Fixed tier charge plus storage overage. No pause tier.';if(t.endsWith('userassignedidentities'))return 'No allocated compute; keep for role assignments.';return 'Review billing for this resource type.'}
function configuration(s:CloudService){const m=s.metrics;if(s.type.toLowerCase().endsWith('sandboxgroups'))return `${m.defaultCpu??'?'} CPU / ${m.defaultMemory??'?'} / ${m.defaultDisk??'?'} · group timeout ${m.defaultTimeoutSeconds??'?'}s · maximum ${m.maxSandboxCount??'?'} · detailed metrics ${m.enableDetailedMetrics?'on':'off'}`;if(s.type.toLowerCase().endsWith('storageaccounts'))return `${s.sku??''} ${m.accessTier??''} · versions ${m.versioning?'on':'off'} · soft delete ${m.soft_delete_days??'?'} days`;if(s.type.toLowerCase().endsWith('registries')){const usage=m.usage as {name:string;currentValue:number;limit:number;unit:string}[]|undefined;return `${s.sku??''} · ${usage?.map(u=>`${u.name}: ${u.unit==='Bytes'?bytes(u.currentValue):u.currentValue} / ${u.unit==='Bytes'?bytes(u.limit):u.limit}`).join(' · ')||'usage unavailable'}`;}return String(m.credential_type??'No configuration metrics available');}
export function ServiceObservations({services,supporting}:{services:ServiceData;supporting:SupportingData}){
 const st=supporting.storage,p=supporting.package_gateway;
 return <><article className="ops-card"><h2>Deployed services</h2><p className="ops-note">Read-only Azure resource-group inventory, refreshed in the background every five minutes. {services.observed_at?`Last observation ${new Date(services.observed_at*1000).toLocaleTimeString()}.`:'Awaiting first cloud observation.'} {services.refreshing?'Refreshing…':''} Resource names are visible only to operators. Group defaults may differ from a workspace’s selected tier.</p>{services.error&&<p role="alert">{services.error}</p>}<div className="ops-table-wrap"><table><thead><tr><th>Service</th><th>Status / region</th><th>Configuration and usage</th><th>Ongoing costs</th></tr></thead><tbody>{services.services.map(s=><tr key={s.type+s.name}><td>{s.name}<small className="ops-note" style={{display:'block'}}>{s.type}</small></td><td>{s.status??'Unknown'} · {s.region}{s.errors.map(e=><p key={e}>{e}</p>)}</td><td>{configuration(s)}</td><td>{policy(s.type)}</td></tr>)}</tbody></table></div><p className="ops-note">No absence is inferred while inventory is unavailable. Resource status is provisioning state, not an application health check.</p></article>
 <div className="ops-columns"><article className="ops-card"><h2>Saved state and archival</h2><p>{bytes(st.current_bytes)} / {bytes(st.max_current_bytes)} indexed Blob data</p><progress aria-label="Blob capacity used" max={st.max_current_bytes} value={st.current_bytes}/><p>{st.checkpoints} / {st.max_objects} checkpoint objects · {st.archived_workspaces} archived workspaces</p><p>{bytes(st.weekly_uploaded_bytes)} / {bytes(st.weekly_upload_limit_bytes)} attempted uploads this week</p><p className="ops-note">Archive after {st.archive_after_days??'disabled'} inactive days. Local indexed bytes exclude older Blob versions and are not Azure billed capacity. Current pilot caps cannot support thousands of retained archives.</p></article>
 <article className="ops-card"><h2>Package gateway and broker</h2>{p.loaded?<><p>{bytes(p.cached_bytes??0)} / {bytes(p.capacity_bytes??0)} package cache</p><progress aria-label="Package cache used" max={p.capacity_bytes} value={p.cached_bytes}/><p>{p.artifacts} cached artifacts · {p.catalog_entries} catalog entries · {p.active_downloads} pinned responses</p><p className="ops-note">{p.minimum_age_days}-day release-age policy remains enforced. Cache eviction preserves active downloads.</p></>:<p>Package gateway has not been loaded.</p>}<p>{supporting.broker.pending_cleanup} pending cleanups · {supporting.broker.sdk_workers} SDK workers · {supporting.broker.active_commands} active commands · {supporting.model.recent_calls} model calls in the past hour</p><p className="ops-note">Frontend, broker, history, package cache and model gateway run locally. Model tokens are billed separately. {supporting.identity.authentication} signs users in; state is {supporting.identity.ownership.toLowerCase()}.</p></article></div></>;
}
