import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Button} from '@/components/ui/button';
import './style.css';
const roles=[
 {name:'Python',cpu:1,ram:4,rate:.03,max:10,detail:'Built-in Python per conversation, with a fresh bounded interpreter per call and durable saved files. Sessions expire after 55 idle minutes; allocated duration rounds up to whole hours. Missing packages use headless projects.'},
 {name:'Headless',cpu:2,ram:4,rate:.216,max:100,detail:'One persistent home per project. All of its chats reuse this home and serialize edits. Model reasoning stays in the local broker; generated code receives no model credential.'},
 {name:'Workstation',cpu:1,ram:2,rate:.108,max:100,detail:'A separate developer home with shared personal editor preferences. Choose 1/2, 2/4 or 4/8 CPU/GiB; changing tier saves files and restarts processes. App previews share its compute. Eligible source syncs with its linked headless project; credentials and packages stay separate.'},
];
function App(){
 const [counts,setCounts]=useState([0,0,0]),[warm,setWarm]=useState(true),[minutes,setMinutes]=useState(5),[selected,setSelected]=useState(1);
 const rate=counts.reduce((sum,n,i)=>sum+n*roles[i].rate,0)+(warm?.324:0);
 const dollars=(v:number)=>v.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:3});
 return <main>
 <header><span className="brand"><span className="brand-mark">S</span>SANDBOX LAB / FIELD GUIDE</span><span className="tag">AZURE SANDBOXES · SEPTEMBER 2026</span></header>
 <section className="intro"><div><div className="eyebrow">EXECUTION, STATE & COST</div><h1>Reuse the work.<br/><em>Release the compute.</em></h1><p>One local interface, independent Azure environments, and a measured warm reserve that drains after the configured idle window.</p></div><div className="intro-stats"><div><strong>10 min</strong><span>sandbox idle / warm window</span></div><div><strong>$12/h</strong><span>test compute guard</span></div><div><strong>$200</strong><span>Azure-only test budget</span></div></div></section>
 <section className="field-section"><h2>Follow the request</h2><div className="flow-grid"><article><small>01 · LOCAL CONTROL</small><h3>Chat → FastAPI broker</h3><p>Owns history, project mapping, jobs, model inference, budgets and the authenticated preview relay. Ordinary chat and documentation reads allocate no project. A local recovery text view preserves conversation access if the embedded chat stalls; it never replays submissions automatically. Workspace/app switching retains the editor frame. Entra sessions renew server-side within eight hours; interactive reconnect preserves the original page.</p></article><article><small>02 · AZURE EXECUTION</small><h3>One of three roles</h3><p>Python boxes are conversation-scoped and deleted after the configured idle window. Headless and developer homes suspend with their state. An app is a process inside its owner’s sandbox, not another Azure deployment.</p></article><article><small>03 · PRESERVED WORK</small><h3>Disks + private Blob</h3><p>Persistent homes retain packages and state. Eligible source and chat working files are checkpointed separately. SQLite and exported artifacts also remain local.</p></article></div></section>
 <section className="field-section"><h2>Choose an execution role</h2><nav className="role-tabs">{roles.map((r,i)=><Button key={r.name} variant={selected===i?'default':'outline'} onClick={()=>setSelected(i)}>{r.name}</Button>)}</nav><article className="role-detail"><h3>{roles[selected].name} · {roles[selected].cpu} CPU / {roles[selected].ram} GiB</h3><p>{roles[selected].detail}</p><strong>{dollars(roles[selected].rate)} / {selected===0?'rounded session-hour':'active hour'}</strong><p>New demand claims a clean spare when available. A used project home is never assigned to another project. Closing a chat does not delete its files.</p></article></section>
 <section className="field-section"><div className="eyebrow">PLANNING CALCULATOR · NOT LIVE BILLING</div><h2>What does concurrency cost?</h2><div className="calc-grid"><div>{roles.map((r,i)=><label className="range-row" key={r.name}><span>{r.name}<strong>{counts[i]} running</strong></span><input type="range" min="0" max={r.max} value={counts[i]} onChange={e=>setCounts(counts.map((v,j)=>j===i?Number(e.target.value):v))}/></label>)}<label className="range-row"><span>Duration<strong>{minutes} minutes</strong></span><input type="range" min="1" max="60" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label><input type="checkbox" checked={warm} onChange={e=>setWarm(e.target.checked)}/> Include one headless and workstation spare</label></div><article className="cost-result"><small>ACTIVE COMPUTE ESTIMATE</small><h3>{dollars(rate)}<span> / hour</span></h3><p>{dollars((rate-counts[0]*.03)*minutes/60+counts[0]*.03*Math.ceil((minutes+55)/60))} including Python’s 55-minute idle tail</p><p className={rate>12?'cost-warning':''}>{rate>12?'Above the current $12/hour testing guard: excess work queues.':'Within the current compute allowance, subject to remaining budget and cloud quota.'}</p><p>Excludes model tokens, registry, storage, transfers, requests and tax. Python includes rounded hours and its idle tail; sandbox estimates include only the selected active duration.</p></article></div></section>
 <section className="field-section"><h2>Warm when useful, asleep when idle</h2><ol className="lifecycle-list"><li><strong>Demand arrives.</strong> Reuse the project home or atomically assign a clean spare. Queue when the role or cost allowance is full.</li><li><strong>Work continues.</strong> Active execution and visible preview use protect the relevant sandbox. Status polling and source-sync traffic do not count as user activity.</li><li><strong>Ten minutes without demand.</strong> Release the role’s spare. Suspend idle persistent workspaces. Python pool sessions use their separate 55-minute idle expiry.</li><li><strong>Seven days inactive.</strong> With archival enabled, verify the saved home in private Blob before removing compute. Reopening rebuilds from the image and restores files; processes and scratch state are not archived. Failures retain the original environment.</li><li><strong>Testing deadline.</strong> Persistent leases expire after 60 minutes even if a page remains open. Reopening reserves another bounded lease. Stop compute pauses warm replenishment and retains saved work.</li></ol></section>
 <section className="field-section"><h2>Regular Container Apps or Sandboxes?</h2><p>Use ordinary Container Apps for a hosted trusted broker and published stateless apps. Keep isolated coding workspaces in Sandboxes for addressable execution, memory suspension and built-in egress policy. Larger Dedicated/GPU profiles add options and cost, not automatic per-user session isolation. Operations charts load on demand; app opens skip editor setup and group inventory.</p></section><section className="field-section"><h2>Pool or Sandbox?</h2><div className="flow-grid two"><article><h3>Sandboxes · current app</h3><p>Direct lifecycle and command/file control, custom disk images, memory/disk suspend, persistent volumes and explicit egress/port policies. Pay for active compute; stopped CPU and memory have no compute fee.</p></article><article><h3>Built-in Dynamic Sessions · quick Python</h3><p>Managed session-ID routing, prewarmed allocation and 55-minute idle expiry. Built-in Python is $0.03 per rounded allocated hour, with no empty-pool node charge. The former custom-container E16 experiment is distinct and remains removed.</p></article></div></section>
 <section className="field-section"><h2>What is measured?</h2><p>Operations records running, warm, busy and queued allocations, allocated CPU/RAM, startup and command durations, failures, completed estimates and open cost reservations. Allocated CPU is not observed CPU utilization. The local ledger is conservative; Azure bills arrive later. A five-minute background ARM inventory reports deployed services, group defaults, registry usage and storage settings. Python returns after saving its checkpoint. Operations separates conservative estimates/reservations from provider billing and operator-reported spend. Owner-scoped workspace model costs use provider usage and cache counters, with UTC calendar periods and explicit unpriced requests. An editor status item reads the same ledger. Open VSX search and eligible downloads travel through the broker; workspace egress remains restricted.</p><p>This is a local broker with tenant-bound Entra sign-in and per-user data. Raised quotas do not validate 100 headless + 100 workstation + 500 Python simultaneous users. The built-in pilot is capped at ten allocated sessions. Production needs shared admission, durable jobs, distributed locks, public gateway hardening and load validation.</p></section>
 <section className="field-section"><h2>Network and identity boundaries</h2><p>Live sandbox egress uses full inspection and default deny. Package traffic follows the trusted age-gated broker. An opt-in Microsoft Learn MCP rule supports approved documentation tools in developer workspaces. Review-only examples demonstrate scoped GitHub PR access, native connector attachment, and managed-identity header injection; a Bicep example scopes Blob read access to one container. Identity belongs to the sandbox group, so privileged groups must not mix unrelated trust boundaries. Ori can route through APIM through its trusted gateway, but that route has not been deployed.</p></section>
 <footer>Source-only, self-contained architecture report · <a href="https://learn.microsoft.com/en-us/azure/container-apps/sandboxes-overview">Microsoft Sandbox documentation</a> · <a href="https://learn.microsoft.com/en-us/azure/container-apps/sessions-custom-container">Custom session documentation</a></footer>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
