import React, {useState} from 'react';

const cases = [
  {id:'build',label:'Ask Pi to build and test an app',result:'Allowed through remote tools',control:'Execution broker',detail:'The managed Pi service requests edits, package installs, tests and a preview. The broker runs them in the bound Coder workspace with a clean environment. Model credentials never accompany the command.',today:'Pi can do this today, but its local process and generated code still share a readable model capability.'},
  {id:'script',label:'A Python script calls the model gateway',result:'Denied from the workspace',control:'Network + service authorization',detail:'The workspace has neither a model token nor a permitted route. A general HTTP client, compiled binary or package hook has the same restriction. Supplying a copied token must not bypass the network boundary.',today:'GUI Pi capabilities remain reusable by scripts. Quick Python and the native Coder headless trial already deny code access to model inference. The separated GUI transport remains a proposal.'},
  {id:'harness',label:'A script calls Pi as its own agent backend',result:'Denied from the workspace',control:'Trusted portal + turn API isolation',detail:'No Pi-service token lives in the VS Code extension host. The workspace cannot reach the turn API or initiate managed agent jobs. A token for Pi would be just as reusable as a token for the model.',today:'Pi Chat currently launches Pi RPC inside the workspace. The managed portal transport is a proposed replacement.'},
  {id:'source',label:'Ask Pi to embed LLM calls in the application',result:'Decline and flag at release review',control:'Authoring policy + final artifact review',detail:'Server-owned policy prohibits LLM integrations. Export/publish checks inspect source, dependencies and the final build, including shell-written and manually edited files. Reviews bind to a digest. Scanning cannot prove the absence of arbitrary disguised calls.',today:'The no-LLM integration release gate is proposed. Runtime isolation and source review solve different parts of the requirement.'},
  {id:'browser',label:'Preview JavaScript calls a trusted chat API',result:'Deny control access; govern browser egress',control:'Separate origins + browser controls',detail:'The preview has no trusted portal credentials. Control APIs enforce identity, ownership, CSRF and origin checks. Browser code runs outside Kubernetes; strict prevention of all external preview traffic needs remote browser rendering or validated enterprise browser controls.',today:'Local previews already isolate origins and strip credentials. Complete browser egress prevention and enterprise SSO need additional design and testing.'},
  {id:'ml',label:'Train a local model for material properties',result:'Allowed within project limits',control:'Ordinary sandbox execution',detail:'Numerical analysis, statistics and conventional local ML remain available. Use uv for approved Python packages and keep data within its approved routes. Prohibiting external LLM integrations does not mean banning data science.',today:'Local analysis works in quick Python or a persistent Coder project, depending on dependencies and task size.'},
];

export function ManagedPiDesign(){
  const [selected,setSelected]=useState('script');
  const item=cases.find(c=>c.id===selected)!;
  return <section className="deep managed-pi">
    <div className="section-label">PROPOSED MIGRATION · NOT THE CURRENT RUNTIME</div>
    <h2>Keep model access in the managed Pi service.</h2>
    <p className="lede">People retain a coding assistant, terminals, packages and previews. The code they build receives no authority to call a model or start its own Pi jobs.</p>
    <div className="three trust-map">
      <article><span className="eyebrow">01 / TRUSTED USER SURFACE</span><h3>Main chat or developer portal</h3><p>SSO stays in the trusted browser origin. Put Pi chat beside VS Code; keep its login outside the workspace extension host.</p><span className="chip">User request → managed job</span></article>
      <article><span className="eyebrow">02 / TRUSTED SERVICES</span><h3>Pi → model gateway</h3><p>Pi's agent loop holds fixed policy and calls OpenRouter through the gateway. All file and command tools call a separate execution broker.</p><span className="chip">Remote tool → bound workspace</span></article>
      <article><span className="eyebrow">03 / UNTRUSTED CODE</span><h3>Coder workspace</h3><p>Languages, packages, files and app processes live here. No model token, Pi-service token, local model proxy or route to the turn API.</p><span className="chip">Tool output → untrusted data</span></article>
    </div>
    <div className="two scenario">
      <article><h3>Follow a request across the boundary</h3><label className="field">Request<select value={selected} onChange={e=>setSelected(e.target.value)}>{cases.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><p>These outcomes describe the proposed architecture. They are not live authorization results.</p><div className="callout"><strong>Local status</strong><p>{item.today}</p></div></article>
      <div className="state-card" aria-live="polite"><div className="eyebrow">{item.control}</div><h3>{item.result}</h3><p>{item.detail}</p></div>
    </div>
    <div className="two"><article><h3>Runtime prevention</h3><p>Code cannot use company-funded inference when it has neither credentials nor direct or indirect access to a model or harness service. Separate pods and identities; never forward the harness environment to a shell. Test package hooks, Coder tunnels, MCP proxies and browser previews.</p></article><article><h3>Authoring and release policy</h3><p>Pi should decline requests to embed LLM integrations. Trusted source and build checks support that rule. Arbitrary general-purpose code can disguise intent, so scans and prompts alone cannot guarantee what a program does. Keep release review and runtime boundaries together.</p></article></div>
    <div className="callout"><strong>Migration scope:</strong> add the Pi SDK remote-tool service and execution broker; change developer chat transport; remove workspace capabilities and routes; then add managed export/publish checks. Keep Kubernetes, Coder, language images, local files and idle policies. The full design and acceptance matrix are in <strong>managed-pi-design.md</strong> under this conversation's files.</div>
  </section>;
}
