import {useState} from 'react';
import {Button} from '@/components/ui/button';

export function ProjectSharing(){
 const [direction,setDirection]=useState('to_chat'),[step,setStep]=useState(0);
 const from=direction==='to_chat'?'Developer workstation':'Chat sandbox',to=direction==='to_chat'?'Chat sandbox':'Developer workstation';
 const steps=[['Linked, not shared','The project links two Coder workspace IDs. Each environment has its own namespace, home PVC, credentials, packages and running processes. A developer link allocates no chat sandbox.'],['Review source','After a chat has requested a project sandbox, Copy to chat / Copy to VS Code wakes both environments and compares eligible source files. The review shows new, matching and different files. No source is written at this step.'],['Approve the copy','The authenticated user approves a five-minute review. The host copies that exact snapshot into a new .lab/imports/transfer_… folder in the destination. It checks hashes and rejects unsafe paths. Existing live source is untouched.'],['Merge deliberately','Ask the destination coding agent to inspect and merge the import, or do so in VS Code. Install dependencies from lockfiles using the destination’s package gateway. Imports do not transfer installed environments, model grants or running apps.']];
 return <section className="deep"><div className="section-label">PROJECTS / SEPARATE EXECUTION · EXPLICIT FILE TRANSFER</div><h2>One project. Two independent places to work.</h2><p className="lede">Main-app chats stay in a headless sandbox. VS Code and Pi remain in the developer workstation. Project membership does not grant either environment the other’s permissions.</p><div className="two"><article><h3>Walk through a transfer</h3><label className="field">Direction<select value={direction} onChange={e=>{setDirection(e.target.value);setStep(0);}}><option value="to_chat">VS Code → Chat</option><option value="to_developer">Chat → VS Code</option></select></label><div className="auth-flow"><span>{from}</span><b>→</b><span>Human review</span><b>→</b><span>{to}</span></div><p>Step {step+1} / 4</p><h3>{steps[step][0]}</h3><p>{steps[step][1]}</p><Button onClick={()=>setStep((step+1)%4)}>{step===3?'Start again':'Next step'}</Button></article><article><h3>Bounded storage and lifecycle</h3><ul><li>At most 2,000 files, 8 MB per file, 32 MB per transfer; traversal stops at 10,000 entries.</li><li>Dependency trees, hidden credential paths, symlinks, build outputs and earlier import folders are excluded.</li><li>Each environment accepts up to three import snapshots. Move or remove an earlier import before another copy; the application does not erase it for you.</li><li>Deleting a project removes its chat data and headless home. A linked developer workstation is retained and unlinked.</li><li>Deleting a developer workstation retains its project and chat sandbox.</li></ul><div className="callout">Filename filters are not full DLP. Production needs Entra ownership, audited transfer approval, secret scanning/content policy, and governed retention. This local UI approval is not an OPA or enterprise identity integration.</div></article></div></section>;
}
